[package]
name = "sic-cranelift"
version.workspace = true
edition.workspace = true

[dependencies]
sic-ir = { path = "../sic-ir" }
cranelift-codegen  = { version = "0.113", features = ["all-arch"] }
cranelift-frontend = "0.113"
cranelift-object   = "0.113"
cranelift-module   = "0.113"
target-lexicon     = "0.12"
cranelift-native   = "0.113"
thiserror          = "1"
